package SuiteRunner;
import org.junit.runner.RunWith;
import org.junit.runners.Suite;

import DiagnoseServices.ValidateComcastWebApplicationAccessiblity.ValidateComcastAppAccessibility.LoginToXidioApplicationWithValidCredentials;
import UserManagement.ProfileManagement.RegisteredUserTestCasesForChangePassword.ResetUserPassword.ResetTheXidioPassword;
import UserManagement.ProfileManagement.RegisteredUserTestCasesForChangePassword.ResetUserPasswordWithInvalidEmail.ResetTheXidioPasswordWithWrongEmail;
import UserManagement.ProfileManagement.RegisteredUserTestCasesForChangePassword.ResetUserPasswordWithNoEmail.ResetXidioPasswordWithoutProvidingEmailID;
import UserManagement.ProfileManagement.RegisteredUserTestCasesForChangePassword.ValidateCurrentUserPassWhileChangingPass.ValidateCurrentPasswordWhenChangingPassword;
import UserManagement.ProfileManagement.RegisteredUserTestCasesForChangePassword.VerifyPasswordChangesSuccessfully.VerifyPasswordChangeWorks;
import UserManagement.ProfileManagement.RegisteredUserTestCasesForChangePaymentInfo.ValidateExpiryMonthField.VerifyPaymentInfoExpiryMonthUpdatedSuccessfully;
import UserManagement.ProfileManagement.RegisteredUserTestCasesForChangePinCode.VerifyChangePinCodeDetailsUpdatedSuccessfully;
import UserManagement.ProfileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateAddressField.EditXidioAddressInProfileManagement;
import UserManagement.ProfileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateCityField.EditXidioCityInProfileManagement;
import UserManagement.ProfileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateFirstNameField.EditXidioFirstNameInProfileManagement;
import UserManagement.ProfileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateFirstNameField.ValidateFirstNameFieldByDeletingValue;
import UserManagement.ProfileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateLastNameField.EditXidioLastNameInProfileManagement;
import UserManagement.ProfileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateStateField.EditXidioStateInProfileManagement;
import UserManagement.ProfileManagement.RegisteredUserTestCasesForEditProfileDetails.ValidateZipField.EditXidioZipInProfileManagement;
import UserManagement.UserLogin.ValidateUserLoginUsingInValidCredentials.LoginToXidioApplicationUsingInValidPassword;
import UserManagement.UserLogin.ValidateUserLoginUsingInValidCredentials.LoginToXidioApplicationUsingInValidUserName;
import UserManagement.UserRegistration.RegisterToXidioApplicationUsingValidCredentials;
import UserManagement.UserRegistration.UserRegistrationTestCasesForActivationCode.UserRegByClickingOnActivationCode.RegisterToXidioApplicationByClickingActivation;
import UserManagement.UserRegistration.UserRegistrationTestCasesForActivationCode.UserRegBySkipingActivationCode.RegisterToXidioApplicationBySkipingPaymentStepAndActivationStep;
import UserManagement.UserRegistration.UserRegistrationTestCasesForAddress.UserRegWithNoAddress.RegisterToXidioApplicationWithoutEnteringAddress;
import UserManagement.UserRegistration.UserRegistrationTestCasesForCity.UserRegWithNoCity.RegisterToXidioApplicationWithoutEnteringCity;
import UserManagement.UserRegistration.UserRegistrationTestCasesForEmail.UserRegWithInvalidEmailID.UserRegWithInvalidEmailIDMissingInputs.RegisterToXidioApplicationByEnteringInValidEmail;
import UserManagement.UserRegistration.UserRegistrationTestCasesForEmail.UserRegWithNoEmailID.RegisterToXidioApplicationWithoutEnteringEmail;
import UserManagement.UserRegistration.UserRegistrationTestCasesForFirstName.UserRegWithNoFirstName.RegisterToXidioApplicationWithoutEnteringFirstName;
import UserManagement.UserRegistration.UserRegistrationTestCasesForLastName.UserRegWithNoLastName.RegisterToXidioApplicationWithoutEnteringLastName;
import UserManagement.UserRegistration.UserRegistrationTestCasesForMobileNumber.UserRegWithInvalidMobileNumber.RegisterToXidioApplicationByEnteringInValidMobileNumber;
import UserManagement.UserRegistration.UserRegistrationTestCasesForMobileNumber.UserRegWithNoMobileNumber.RegisterToXidioApplicationWithoutEnteringMobileNumber;
import UserManagement.UserRegistration.UserRegistrationTestCasesForPassword.UserRegWithInvalidPasswordLength.RegisterToXidioApplicationByEnteringInValidLengthOfPassword;
import UserManagement.UserRegistration.UserRegistrationTestCasesForPassword.UserRegWithNoFirstCapitalLetter.RegisterToXidioApplicationByEnteringNonCapitalLetterPassword;
import UserManagement.UserRegistration.UserRegistrationTestCasesForPassword.UserRegWithNoPassword.RegisterToXidioApplicationWithoutEnteringPassword;
import UserManagement.UserRegistration.UserRegistrationTestCasesForPassword.UserRegWithNonDigitPassword.RegisterToXidioApplicationByEnteringNonDigitPassword;
import UserManagement.UserRegistration.UserRegistrationTestCasesForPaymentDetails.RegisterToXidioApplicationDirectlyWithPaymentDetailsWithoutPersonalInfo;
import UserManagement.UserRegistration.UserRegistrationTestCasesForTermsAndCondition.UserRegByDeclineTermAndCondition.RegisterToXidioApplicationWithValidCredentialByDeclineTermAndCondition;
import UserManagement.UserRegistration.UserRegistrationTestCasesForZipCode.UserRegWithInvalidZipCode.RegisterToXidioApplicationByEnteringInValidZip;
import UserManagement.UserRegistration.UserRegistrationTestCasesForZipCode.UserRegWithInvalidZipCodeLength.RegisterToXidioApplicationByEnteringInValidZipLength;
import UserManagement.UserRegistration.UserRegistrationTestCasesForZipCode.UserRegWithNoZipCode.RegisterToXidioApplicationWithoutEnteringZip;
import VideoManagement.VideoFeedBackManagement.VerifyFeedbackSubmitedSuccessfully;
import VideoManagement.VideoSearchFunctionality.SearchVideoByCategory.EnsureSearchChannelStoreIsWorkingFine;
import VideoManagement.VideoSearchFunctionality.SearchVideoByCategory.VerifySelectedCategoryAndSubCategoryVideosAreDisplayed;
import VideoManagement.VideoSubscriptionManagement.PaidSubscriptionForVideo.VerifySubcriptionOfPaidVideo;

@RunWith(Suite.class)
@Suite.SuiteClasses({
	//Start Registration Module....
	RegisterToXidioApplicationByClickingActivation.class,
	RegisterToXidioApplicationByEnteringInValidEmail.class,
	RegisterToXidioApplicationByEnteringInValidLengthOfPassword.class,
	RegisterToXidioApplicationByEnteringInValidMobileNumber.class,
	RegisterToXidioApplicationByEnteringInValidZip.class,
	RegisterToXidioApplicationByEnteringInValidZipLength.class,
	RegisterToXidioApplicationByEnteringNonCapitalLetterPassword.class,
	RegisterToXidioApplicationByEnteringNonDigitPassword.class,
	RegisterToXidioApplicationBySkipingPaymentStepAndActivationStep.class,
	RegisterToXidioApplicationDirectlyWithPaymentDetailsWithoutPersonalInfo.class,
	RegisterToXidioApplicationUsingValidCredentials.class,
	RegisterToXidioApplicationWithoutEnteringAddress.class,
	RegisterToXidioApplicationWithoutEnteringCity.class,
	RegisterToXidioApplicationWithoutEnteringEmail.class,
	RegisterToXidioApplicationWithoutEnteringFirstName.class,
	RegisterToXidioApplicationWithoutEnteringLastName.class,
	RegisterToXidioApplicationWithoutEnteringMobileNumber.class,
	RegisterToXidioApplicationWithoutEnteringPassword.class,
	RegisterToXidioApplicationWithoutEnteringZip.class,
	RegisterToXidioApplicationWithValidCredentialByDeclineTermAndCondition.class,
	//End Start Registration Module....
	
	//Start Profile Module....
	ValidateCurrentPasswordWhenChangingPassword.class,
	VerifyPasswordChangeWorks.class,
	VerifyPaymentInfoExpiryMonthUpdatedSuccessfully.class,
	VerifyChangePinCodeDetailsUpdatedSuccessfully.class,
	EditXidioAddressInProfileManagement.class,
	EditXidioCityInProfileManagement.class,
	EditXidioLastNameInProfileManagement.class,
	EditXidioStateInProfileManagement.class,
	EditXidioFirstNameInProfileManagement.class,
	EditXidioZipInProfileManagement.class,
	ValidateFirstNameFieldByDeletingValue.class,
	//End Profile Module....
	
	//Start Profile Module....
	ResetTheXidioPassword.class,
	ResetTheXidioPasswordWithWrongEmail.class,
	ResetXidioPasswordWithoutProvidingEmailID.class,
	LoginToXidioApplicationUsingInValidPassword.class,
	LoginToXidioApplicationUsingInValidUserName.class,
	LoginToXidioApplicationWithValidCredentials.class,
	
	//Start Video Management Module....
	VerifyFeedbackSubmitedSuccessfully.class,
	EnsureSearchChannelStoreIsWorkingFine.class,
	VerifySelectedCategoryAndSubCategoryVideosAreDisplayed.class,
	VerifySubcriptionOfPaidVideo.class
	//Start Video Management Module....
	
	
})
public class runATFRegression {

}

